[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.9.0", features = ["canvas"] }
rand = "0.8.5"

# Need to specify the feature to support wasm
getrandom = { version = "0.2", features = ["js"] }

[profile.release]
opt-level = 's'
lto = true

# trunk serve
# trunk build --release
